name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16', '18']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node JS ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Update NPM
        run: npm install -g npm

      - name: Show Node/NPM versions
        run: |
          node --version
          npm --version

      - name: Install
        run: npm ci --engine-strict --strict-peer-deps

      - name: Lint
        run: |
          npm run prettier:check
          npm run lint

      - name: Run tests
        run: npm test
